### ISSUE TITLE
class for the breakout

### ISSUE THREAD

**Issue by AndiCui** [pimoroni/displayotron#41]
I think it will be really nice to have a standalone class for the breakout board
Like this.
```python
from dotbreakout import blah
```

It will make a lot of sense if you can set the pins used without changing the library and setup PWM with just something like `backlight.foo()`

**Comment by Gadgetoid** [comment]
This is definitely needed, see: https://forums.pimoroni.com/t/display-o-tron-rgb-breakout-doesnt-work/6001/7

**Comment by Gadgetoid** [comment]
Closing to help clear my proverbial desk, since this is _ancient_!
