### ISSUE TITLE
Default contrast value for Display-O-Tron HAT

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/displayotron#57]
The default contrast value seems much too low. I'd suggest setting the default to 50 in the library itself, or at the top of each example with `lcd.set_contrast(50)`.

**Comment by Gadgetoid** [comment]
I think this has either been fixed since, or is only an issue in certain cases. I'd have expected more of a ruckus here otherwise. Closing since this issue is soooo stale!
